version: '3.3'
services:
  envoy:
    image: envoyproxy/envoy:v1.23-latest
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      - ENVOY_UID=0
      - ENVOY_GID=0
    ports:
      - "8080:8080"
      - "9901:9901"
    networks:
      envoymesh:
        ipv4_address: 172.31.4.8
        aliases:
        - front-proxy
    depends_on:
    - webserver01
    - webserver02
    
  webserver01:
    image: docker.io/cloudbennie/http-server:1.0
    network_mode: "service:webserver01-sidecar"
    depends_on:
    - webserver01-sidecar
  webserver01-sidecar:
    image: envoyproxy/envoy:v1.23-latest
    hostname: webserver01
    networks:
      envoymesh:
        ipv4_address: 172.31.4.11
        aliases:
        - webserver01    
    volumes:
    - ./envoy-sidecar-proxy.yaml:/etc/envoy/envoy.yaml 

  webserver02:
    image: docker.io/cloudbennie/http-server:1.0
    network_mode: "service:webserver02-sidecar"
    depends_on:
    - webserver02-sidecar
  webserver02-sidecar:
    image: envoyproxy/envoy:v1.23-latest
    hostname: webserver02
    networks:
      envoymesh:
        ipv4_address: 172.31.4.12
        aliases:
        - webserver02
    volumes:
    - ./envoy-sidecar-proxy.yaml:/etc/envoy/envoy.yaml 


networks:
  envoymesh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.4.0/24
